l3_interfaces:
-   ipv4:
    -   address: dhcp
    name: Ethernet1
-   ipv4:
    -   address: 192.168.4.4/32
    name: Loopback0
-   ipv4:
    -   address: 10.10.10.10/32
    name: Loopback200
-   ipv4:
    -   address: 10.10.10.11/32
    name: Loopback201   
-   ipv4:
    -   address: 10.101.101.4/24
    name: Tunnel0
