l3_interfaces:
-   ipv4:
    -   dhcp:
            enable: true
    name: GigabitEthernet1
-   ipv4:
    -   address: 192.168.1.1/32
    name: Loopback0
-   ipv4:
    -   address: 10.100.100.1/24
    name: Tunnel0
-   ipv4:
    -   address: 10.200.200.1/24
    name: Tunnel1
-   ipv4:
    -   address: 192.168.35.101/24
    name: VirtualPortGroup0
