l3_interfaces:
-   ipv4:
    -   address: dhcp
    name: Ethernet1
-   ipv4:
    -   address: 192.168.2.2/32
    name: Loopback0
-   ipv4:
    -   address: 10.101.101.2/24
    name: Tunnel0
-   ipv4:
    -   address: 10.200.200.2/24
    name: Tunnel1
